<?php

namespace Packt\HelloWorld\Block\Customer;

use Magento\Framework\View\Element\Template;

class Lists extends \Magento\Framework\View\Element\Template
{
    public function __construct(
        Template\Context $context,
        array $layoutProcessors = [],
        array $data = []
    )
    {
        parent::__construct($context, $data);
        $this->layoutProcessors = $layoutProcessors;
    }
    public function getJsLayout()
    {
        foreach ($this->layoutProcessors as $processor) {
            $this->jsLayout = $processor->process($this->jsLayout);
        }
        return parent::getJsLayout(); // TODO: Change the autogenerated stub
    }
}