<div id="test-div" data-bind="scope:'test'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#test-div": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
           }
       }
   </script>

    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
<!--<div data-bind="scope: 'customcomponent'">-->
<!--    <!-- ko template: getTemplate() --><!-- /ko -->-->
<!--</div>-->
<!---->
<!--<script type="text/x-magento-init">-->
<!--        {-->
<!--            "*": {-->
<!--                "Magento_Ui/js/core/app": {-->
<!--                    "components": {-->
<!--                        "customcomponent": {-->
<!--                            "component": "Packt_HelloWorld/js/custom-component",-->
<!--                            "template" : "Packt_HelloWorld/knockout-test"-->
<!--                        }-->
<!--                    }-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--</script>-->

<!--View-->
<!--<div id="custom-component" data-bind="scope:'customcomponent'">-->
<!--    <!-- ko template: getTemplate() --><!-- /ko -->-->
<!--    <script type="text/x-magento-init">-->
<!--    {-->
<!--        "#custom-component": {-->
<!--            "Magento_Ui/js/core/app": {-->
<!--               "components": {-->
<!--                    "customcomponent": {-->
<!--                        "component": "Packt_HelloWorld/js/custom-component"-->
<!--                    }-->
<!--                }-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--    </script>-->
<!--</div>-->